<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_theme().
 */
function islandora_pdfjs_theme() {
  return [
    'islandora_pdfjs' => [
      'file' => 'theme/theme.inc',
      'variables' => [
        'fedora_object' => NULL,
        'dsid' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_pdfjs_islandora_viewer_info() {
  return [
    'islandora_pdfjs' => [
      'label' => t('pdf.js Reader'),
      'description' => t('Mozilla pdf.js Reader.'),
      'configuration' => '',
      'callback' => 'islandora_pdfjs_viewer_callback',
      'model' => [
        'islandora:sp_pdf',
        'islandora:bookCModel',
        'islandora:pageCModel',
        'islandora:newspaperIssueCModel',
      ],
      'mimetype' => ['application/pdf'],
    ],
  ];
}

/**
 * Callback function for the viewer.
 *
 * @param array $params
 *   The params for the theme function 'islandora_pdfjs'.
 * @param AbstractObject|null $fedora_object
 *   The object that we are viewing.
 *
 * @return string
 *   HTML repersentation of the pdf.js Reader.
 */
function islandora_pdfjs_viewer_callback(array $params, $fedora_object = NULL) {
  $dsid = NULL;
  if (isset($params['dsid']) && !empty($params['dsid']) && isset($fedora_object[$params['dsid']])) {
    $dsid = $params['dsid'];
  }
  else {
    if (isset($fedora_object['PDF'])) {
      $dsid = 'PDF';
    }
    elseif (isset($fedora_object['OBJ']) && $fedora_object['OBJ']->mimetype == 'application/pdf') {
      $dsid = 'OBJ';
    }
  }
  if ($dsid && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $fedora_object[$dsid])) {
    $render_array = [
      '#theme' => 'islandora_pdfjs',
      '#fedora_object' => $fedora_object,
      '#dsid' => $dsid,
    ];
    return \Drupal::service('renderer')->render($render_array);
  }
}
